# 2D Numpy

In [1]:
# Import the libraries
import numpy as np

In [2]:
# Consider the list a, which contains three nested lists each of equal size
a = [[11,12,13], [21,22,23], [31,32,33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [3]:
# Convert list to Numpy Array
# Every element is the same type
A = np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [5]:
# Show the numpy array dimensions
A.ndim     # 2 brackets/ 2 Axes

2

In [7]:
# Show the numpy array shape
A.shape

(3, 3)

In [8]:
# Show the numpy array size
A.size

9

## Accessing different elements of a Numpy Array

In [9]:
# Access the element on the second row and third column
A[1,2]

23

In [10]:
# Access the element on the second row and third column
A[1][2]

23

In [11]:
# Access the element on the first row and first column
A[0][0]

11

In [15]:
# Access the element on the first row and first and second columns
A[0][0:2]

array([11, 12])

In [17]:
# Access the element on the first and second rows and third column
A[0:2,2]

array([13, 23])

## Basic Operations

In [18]:
# Create a numpy array X
X = np.array([[1,0], [0,1]])
X

array([[1, 0],
       [0, 1]])

In [19]:
# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]])
Y

array([[2, 1],
       [1, 2]])

In [20]:
# Add X and Y
Z = X + Y
Z

array([[3, 1],
       [1, 3]])

In [22]:
# Multiply Y with 2
Z = 2*Y
Z

array([[4, 2],
       [2, 4]])

In [23]:
# Multiply X with Y
Z = X*Y
Z

array([[2, 0],
       [0, 2]])

In [26]:
# Create a matrix A
A = np.array([[0,1,1],[1,0,1]])
A

array([[0, 1, 1],
       [1, 0, 1]])

In [27]:
# Create a matrix B

B = np.array([[1, 1], [1, 1], [-1, 1]])
B

array([[ 1,  1],
       [ 1,  1],
       [-1,  1]])

In [28]:
# Calculate the dot product
Z = np.dot(A,B)
Z

array([[0, 2],
       [0, 2]])

In [29]:
# Calculate the sine of Z
np.sin(Z)

array([[0.        , 0.90929743],
       [0.        , 0.90929743]])

In [30]:
# Create a matrix C

C = np.array([[1,1],[2,2],[3,3]])
C

array([[1, 1],
       [2, 2],
       [3, 3]])

In [31]:
# Get the transposed of C
C.T

array([[1, 2, 3],
       [1, 2, 3]])

## Quiz on 2D Numpy Array

In [32]:
# Consider the following list a, convert it to Numpy Array
a = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]

In [34]:
A = np.array(a)
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [35]:
# Calculate the numpy array size.
A.size

12

In [37]:
# Access the element on the first row and first and second columns.
A[0,0:2]

array([1, 2])

In [42]:
# Perform matrix multiplication with the numpy arrays A and B.
B = np.array([[0,1],[1,0],[1,1],[-1,0]])
B

array([[ 0,  1],
       [ 1,  0],
       [ 1,  1],
       [-1,  0]])

In [41]:
X = np.dot(A,B)
X

array([[ 1,  4],
       [ 5, 12],
       [ 9, 20]])

0+2+3-4    1+0+3+0
0+6+7-8    5+0+7+0
0+10+11-12  9+0+11+0


Ans :1    4
     5   12
     9    20

|Operation|	Description|	Example|
|------|------|------|
|Array Creation	|Creating a NumPy array.|	arr = np.array([1, 2, 3, 4, 5])|
|Element-Wise Arithmetic|	Element-wise addition, subtraction, and so on.|	result = arr1 + arr2|
|Scalar Arithmetic|	Scalar addition, subtraction, and so on.|	result = arr * 2|
|Element-Wise Functions	|Applying functions to each element.|	result = np.sqrt(arr)|
|Sum and Mean	|Calculating the sum and mean of an array.Calculating the sum and mean of an array.|	total = np.sum(arr)<br>average = np.mean(arr)|
|Maximum and Minimum Values|	Finding the maximum and minimum values.|	max_val = np.max(arr)<br>min_val = np.min(arr)|
|Reshaping|	Changing the shape of an array.|	reshaped_arr = arr.reshape(2, 3)|
|Transposition	|Transposing a multi-dimensional array.|	transposed_arr = arr.T|
|Matrix Multiplication|	Performing matrix multiplication.|	result = np.dot(matrix1, matrix2)|